### ISSUE TITLE
 https://github.com/scholi/pySPM_data.  This URL could not be found .

### ISSUE THREAD

**Issue by xx2294** [scholi/pySPM#13]
**Describe the bug**

**To Reproduce**
Snippet of code creating the error

**Expected behavior**

**Screenshots**

**Information:**
 - OS: [e.g. windows]
- Python and pySPM version.

Please run the following and attach the result to your issue
```python
import sys
import pySPM
import numpy as np
import scipy
import matplotlib as mpl
print("Python",sys.version)
print("pySPM",pySPM.__version__)
print("numpy",np.__version__)
print("scipy",scipy.__version__)
print("matplotlib", mpl.__version__)
```

**Additional context**

**Comment by scholi** [comment]
What is the bug? It's normal that this url does not exists.

**Comment by xx2294** [comment]
> What is the bug? It's normal that this url does not exists.
> 
> Where did you found this link?

Hello! I found this link in the Document. I want to download the pySPM_data library which provides all example data files, but according to your link (https://github.com/scholi/pySPM_data) it can't be open.  It seems that the information has been deleted?

**Comment by xx2294** [comment]
Could you provide  the pySPM_data library for me? Thank you very much!

**Comment by scholi** [comment]
Ah yes right. Thank you for spotting it. I'll try to fix it.
In the meantime just read the Readme till the very end and you will discover the proper link.

**Comment by xx2294** [comment]
Looking forward to your link! Thank you for your help again!

**Comment by scholi** [comment]
The link for pySPM_data is in the readme. You even made a nice screenshot of the link ;)

**Comment by xx2294** [comment]
I know the link for pySPM_data is in the readme, but the link is invaild.
![image](https://user-images.githubusercontent.com/52774544/70196425-9ea3bd00-1743-11ea-89a4-fa3d0ff0a1cd.png)
