### ISSUE TITLE
D:\Anaconda\lib\site-packages\pySPM\data\CristA_0002.xml

### ISSUE THREAD

**Issue by xx2294** [scholi/pySPM#14]
Sorry to bother you again！
![image](https://user-images.githubusercontent.com/52774544/70128109-4626de00-16b7-11ea-8510-509eab2b4bd7.png)
In the 'data' directory, I couldn't find the file called CristA_0002.xml.
Thank you!

**Comment by scholi** [comment]
It is not supposed to be there. The data are part of the **pySPM_data** package, not pySPM as you show in your screenshot. There is also a python function to load them, but for that you need to install them and not have them laying around in your download folder as in your screenshot.

**Comment by xx2294** [comment]
Where can I download pySPM_data package for subsequent installations?
Thank you for yor answer!

**Comment by scholi** [comment]
Question already answered see #13
