### ISSUE TITLE
Scaling parts of the spectrum 

### ISSUE THREAD

**Issue by mw00847** [scholi/pySPM#15]
When using A.ShowSpectrum() is it possible to scale the spectrum to account for differences in intensity. As shown in the image.

![](https://i.stack.imgur.com/APuay.png)

Thanks

**Comment by scholi** [comment]
Hi. I think theire is no such function, but you can recover both mass, intensity vector with
```python
mass, intensity = A.get_spectrum()
```

and do the scaling and plotting with matplotlib as you like

**Comment by scholi** [comment]
As an example

```python
import matplotlib.pyplot as plt
m, I = A.get_spectrum()
m_thresh=80
plt.plot(m[m<=m_thresh], I[m<=m_thresh])*3)
plt.plot(m[m>m_thresh], I[m>m_thresh])*3)
```

of course you should also add the legend "×3"

**Comment by mw00847** [comment]
thanks
