### ISSUE TITLE
Wired z axis values

### ISSUE THREAD

**Issue by Thoronfin** [scholi/pySPM#16]
Hi,

the z scale (height) values from my code seems a bit wired.

```
filename="CaptureFile.0_00019.spm"
ScanB = pySPM.Bruker(filename)
Height = ScanB.get_channel("Height")
Height2 = Height.correct_plane(inline=False)
fig, ax = plt.subplots(1,1, figsize=(5,5))
p=Height2.zero_min().show(ax=ax, cmap="inferno", title="")
cbar=plt.colorbar(p,fraction=0.046)
cbar.set_label(label=Height2.zscale,rotation=270, labelpad=10)
plt.tight_layout()
```

This is the result from the code:
![Python Code Output](https://user-images.githubusercontent.com/41733733/104603725-9ae7a700-5674-11eb-980b-b796927a681b.png)

This is the same picture opened through Gwyddion:
<img width="448" alt="Gwyddion Output" src="https://user-images.githubusercontent.com/41733733/104603663-8c00f480-5674-11eb-9678-d1531244f564.PNG">

This is the source file:
[CaptureFile.0_00019.zip](https://github.com/scholi/pySPM/files/5815013/CaptureFile.0_00019.zip)

I plotted the same graphs using a file from an other issue (see below). In that file there is a

> [ZSensor] "Height Sensor" 

and the python plot is identical to the Gwyddion graph.

[e17089.0_00001.zip](https://github.com/scholi/pySPM/files/5815064/e17089.0_00001.zip)

Cheers

**Comment by scholi** [comment]
Hi,
Yes there is some issue with the Bruker files.Bruker changed there file format with time and have some encoding issue. I don't have access to an instrument, so I cannot do any testing. If someone can find and correct the problem he can send a push request and I'll merge it to the library

**Comment by scholi** [comment]
This issue a a duplicata of https://github.com/scholi/pySPM/issues/7 ⇒ closing this one

**Comment by scholi** [comment]
I have fixed the library. Please update and test
![image](https://user-images.githubusercontent.com/988485/105600347-1512dc80-5d95-11eb-9eee-4a4cf9c5d980.png)

**Comment by Thoronfin** [comment]
Thanks, it seems work
