### ISSUE TITLE
Nonsquare scans Bruker files (.spm)

### ISSUE THREAD

**Issue by GGGGGuillaume** [scholi/pySPM#22]
Hello, thank you very much for your work, it is great (and very time efficient) to reopen the Bruker files with python ! 

I have a little trouble with opening scans that are non square (where the aspect ratio is not 1:1).  For example, I have a 2:1 aspect ratio scan, X size is 10 µm and Y size = X size/2 = 5 µm, 256 pixels in X, 128 pixels in Y. When I use pySPM, the scan becomes a 10*10 µm scan...

Thanks in advance,

Guillaume

**Comment by scholi** [comment]
Can you send me some data to test it?

**Comment by GGGGGuillaume** [comment]
[scan_test.zip](https://github.com/scholi/pySPM/files/7586450/scan_test.zip)

Of course, cf. attached file !

**Comment by scholi** [comment]
I found that Bruker is using an Aspect Ratio info and could fix it so that it works for the example you have sent me.
Unfortunately I don't have access to data anymore. Could you pull the git (not pip) and make some tests to see if the results makes sense?

**Comment by scholi** [comment]
```python
from pySPM import Bruker
import os.path

b = Bruker(os.path.expanduser("~/desktop/scan_test.spm"))
c = b.get_channel("Height", debug=True)
c.show()
```
![image](https://user-images.githubusercontent.com/988485/143312141-84482b05-0adb-43fb-8ba6-47527c741d38.png)

**Comment by GGGGGuillaume** [comment]
I have tested it with a few scans (different aspect ratios), it works perfectly ! Thanks you very much for your quick assistance (and thanks again for the library, it will be very useful for me).
![aspectratio10](https://user-images.githubusercontent.com/94835072/143474678-55b4c24f-033c-49a4-af2e-145b8b1c139c.png)
