### ISSUE TITLE
Question: basic plotting code

### ISSUE THREAD

**Issue by santimirandarp** [scholi/pySPM#28]
Not really a python user and trying to plot a basic SPM image. This is what I did:
```
from pySPM import *
a = Bruker("./pathTo/file.spm")
a.list_channels() # S [ZSensor] "Height Sensor"

a.get_channel("Height Sensor").show() 
<matplotlib.image.AxesImage object at 0x7fdd15970790>

# but nothing shows
```

The pixels are logged as an array type of object so I don't know what I am missing here. Would be good to just get some hint.

PD: Also tried `plt.show()` but it isn't really an image of the data, just a color gradient.

**Comment by scholi** [comment]
I think you are missing:
`plt.show()`
