### ISSUE TITLE
Bruker get_channel floating point parsing error

### ISSUE THREAD

**Issue by SylviaWhittle** [scholi/pySPM#38]
**Describe the bug**
Hi there 😄 

We have been using pySPM for a while now to open Bruker .spm files, and it has been going seamlessly. Today we have noticed that on files that previously definitely loaded properly, it now throws this error. The files are non-square in their aspect ratio.

The issue appears to be the handling of floating point values in the `get_channel()` method of the `Bruker` class.

What is weird is that this error happens on both version `0.2.23` and `0.5.1` and manually setting the versions to previous versions does not fix it.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], [line 7](vscode-notebook-cell:?execution_count=9&line=7)
      [3](vscode-notebook-cell:?execution_count=9&line=3) data = pySPM.Bruker(file)
      [5](vscode-notebook-cell:?execution_count=9&line=5) data.list_channels()
----> [7](vscode-notebook-cell:?execution_count=9&line=7) height = data.get_channel('Height')

File [/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:173](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:173), in Bruker.get_channel(self, channel, backward, corr, debug, encoding, lazy, mfm)
    [171](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:171)     print("xres/yres", xres, yres)
    [172](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:172) scan_size = self.layers[i][b'Scan Size'][0].split()
--> [173](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:173) aspect_ratio = [int(x) for x in self.layers[i][b'Aspect Ratio'][0].split(b":")]
    [174](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:174) if debug:
    [175](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:175)     print("aspect ratio", aspect_ratio)

File [/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:173](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:173), in <listcomp>(.0)
    [171](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:171)     print("xres/yres", xres, yres)
    [172](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:172) scan_size = self.layers[i][b'Scan Size'][0].split()
--> [173](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:173) aspect_ratio = [int(x) for x in self.layers[i][b'Aspect Ratio'][0].split(b":")]
    [174](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:174) if debug:
    [175](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/new/lib/python3.10/site-packages/pySPM/Bruker.py:175)     print("aspect ratio", aspect_ratio)

ValueError: invalid literal for int() with base 10: b'0.51216'
```

**To Reproduce**
file used:
[not_working_file.spm.zip](https://github.com/scholi/pySPM/files/13875221/not_working_file.spm.zip)

I had to compress it since GitHub won't allow `.spm` uploads. I hope this doesn't corrupt it.

```python
from pathlib import Path

import pySPM

print("pySPM version: ", pySPM.__version__)

file = Path('/Users/sylvi/Downloads/not_working_file.spm')

data = pySPM.Bruker(file)

data.list_channels()

height = data.get_channel('Height')
```

**Expected behavior**
Loading the height channel data as usual.

**Screenshots**
![image](https://github.com/scholi/pySPM/assets/86117496/90ca7de4-91cd-4fbe-bf4f-d670f6166093)

**Information:**

- OS: Windows 10 (intel x86), macOS Sonoma (ARM M1 Pro) 
- Python version: 3.10.9
- PySPM version: 0.5.1

Please run the following and attach the result to your issue

```python
import sys
import pySPM
import numpy as np
import scipy
import matplotlib as mpl
print("Python",sys.version)
print("pySPM",pySPM.__version__)
print("numpy",np.__version__)
print("scipy",scipy.__version__)
print("matplotlib", mpl.__version__)
```

```
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
pySPM 0.5.1
numpy 1.26.3
scipy 1.10.1
matplotlib 3.7.1
```

**Comment by scholi** [comment]
It seems that the aspect ratio is a float and not a pair of int.
Is this picture correct or the aspect ratio is the otherway arround?
![image](https://github.com/scholi/pySPM/assets/988485/069c207c-5bc2-439b-8880-8d307d700584)

**Comment by SylviaWhittle** [comment]
Thank you for your attention

B is correct.

I have been told that we have successfully used pySPM on these images before which is strange... It seems that it shouldn't have ever worked if the code assumed a pair of integers.

**Comment by scholi** [comment]
What is the real size of your image? 300μm horizontally? but for the vertical axis Gwyddion tells me about 210μm while the aspect ratio of 0.51216 of 300μm is 153μm which is strange...

**Comment by SylviaWhittle** [comment]
The real size of the image as reported by Nanoscope, are 300nm x 210nm (0.7 aspect ratio)
![image](https://github.com/scholi/pySPM/assets/86117496/93bd2d5a-67cf-420c-92d2-2389e4b2d65c)

I also held a tape measure up to my screen and confirmed an aspect ratio of 0.7.

We have no idea where the 0.51216 aspect ratio could come from. It is very strange. It is also strange that these files loaded perfectly fine before about December 22nd 2023. Perhaps there is some user error in there somewhere...

Your branch works on both the files that were not previously able to be loaded. I cannot share the second one as it is a collaborator's data and we don't have permission to share it.

Here is a screenshot of it working:
![image](https://github.com/scholi/pySPM/assets/86117496/95452810-0175-4fbe-84e6-3a137d0750ac)


Thank you for your time, it is very much appreciated by our team 😄

**Comment by scholi** [comment]
Ok good to hear that it works :). So I will merge this branch to master.
