### ISSUE TITLE
Need Engage X and Y Pos info

### ISSUE THREAD

**Issue by nihtmusic** [scholi/pySPM#40]
I'm trying to pull out "Engage X Pos" and "Engage Y Pos" from a bruker file.

<img width="232" alt="parameter lists" src="https://github.com/scholi/pySPM/assets/57849582/0b9ec91e-6a04-4365-b8ac-bf1c076d267f">

I don't see this in the existing list I get from layers:

<img width="219" alt="existing list" src="https://github.com/scholi/pySPM/assets/57849582/a8277e85-158e-48c8-84dc-f1019075877e">

Is there another way to get that info from the file?  It seems you are mostly only pulling the Ciao image list...not the File List shown in the first image that is a screen shot of nanoscope. 

Thanks,

Kurt

**Comment by dineshpinto** [comment]
You can try and manually parse the information, example snippet:

```python
import pySPM

with open("<path to afm file>", "rb") as f:
    line = f.readline().rstrip().replace(b"\\", b"")
    while line != b"*File list end":
        line = f.readline().rstrip().replace(b"\\", b"")
        if b"Engage X Pos" in line or b"Engage Y Pos" in line:
            print(line)
```

from which you can extract the number and unit.

**Comment by nihtmusic** [comment]
Hey!  That worked!  Thank you!

Kurt
