### ISSUE TITLE
get_channel("Height") issue

### ISSUE THREAD

**Issue by nihtmusic** [scholi/pySPM#41]
One more issue I am running into that not being able to view height channel.  I am able to get .list_channels() to work, but .get_channel("Height") is not working.  Below is a screen shot of my jupyter notebook showing the error:

<img width="485" alt="height channel error" src="https://github.com/scholi/pySPM/assets/57849582/f5873047-3132-4a5a-8736-0246c6b7b0d6">

This file version is v5.15b7 if that helps.  

Thank you,

Kurt

**Comment by nihtmusic** [comment]
One more thing...if I just do a vanilla get_channel() I get the following errors:  

<img width="490" alt="get_channel" src="https://github.com/scholi/pySPM/assets/57849582/b14de597-c4a7-42a5-bb22-4bc202eddfbf">

**Comment by dineshpinto** [comment]
If you send me the Bruker file (annual.fallout_0z@icloud.com), I can take a look

**Comment by scholi** [comment]
You should do a `afm_image.list_channels()` then you will know what is available

**Comment by nihtmusic** [comment]
> If you send me the Bruker file ([annual.fallout_0z@icloud.com](mailto:annual.fallout_0z@icloud.com)), I can take a look

Sorry for the delay.  I will send the file to you shortly.  Thanks for taking a look.  -Kurt

**Comment by nihtmusic** [comment]
> You should do a `afm_image.list_channels()` then you will know what is available

I did that as shown in the first post in this thread.  That works...and "Height" is there.  But  .get_channel("Height") doesn't work:  

![response2](https://github.com/scholi/pySPM/assets/57849582/05a356b3-6628-45a6-bf04-f0323207998e)

**Comment by dineshpinto** [comment]
So the file defines "Line direction" not "Line Direction", which is a trivial bugfix.

However, it looks like the byte packing of the file differs from a standard Bruker file. From the file you sent:

```ipython
>>> afm = pySPM.Bruker("junk.002")
>>> afm.list_channels()
Channels
========
S [Height] "Height"
>>> byte_length = int(afm.layers[0][b"Data length"][0])
32768
>>> cols = int(afm.layers[0][b"Number of lines"][0])
512
>>> rows = int(afm.layers[0][b"Samps/line"][0])
512
```

This is causing a problem as  `Bruker._get_raw_layer()` calculates bytes per pixel as `bpp = byte_length // (rows * cols)`, which here is `32768//(512*512) = 0`, which is obviously incorrect.

Querying bpp directly:

```ipython
>>> int(self.layers[i][b"Bytes/pixel"][0])
2
```

Could the file be corrupted or in a different format than expected, @scholi do you have any idea?

**Comment by scholi** [comment]
The bpp info is confusion and this is confirmed by the source code of Gwyddion: https://github.com/christian-sahlmann/gwyddion/blob/master/modules/file/nanoscope.c

The importand part is:
```c 
/* Bytes/pixel determines the scaling factor, not actual raw data type.
     * This is what Bruker people say. */
    val = g_hash_table_lookup(hash, "Bytes/pixel");
    qbpp = val ? GWY_ROUND(val->hard_value) : 2;

    bpp = 2;
    if (file_type == NANOSCOPE_FILE_TYPE_BIN32)
        bpp = 4;
```

and

```c
typedef enum {
    NANOSCOPE_FILE_TYPE_NONE = 0,
    NANOSCOPE_FILE_TYPE_BIN,
    NANOSCOPE_FILE_TYPE_BIN32,
    NANOSCOPE_FILE_TYPE_TXT,
    NANOSCOPE_FILE_TYPE_FORCE_BIN,
    NANOSCOPE_FILE_TYPE_FORCE_BIN32,
    NANOSCOPE_FILE_TYPE_FORCE_VOLUME,
    NANOSCOPE_FILE_TYPE_FORCE_VOLUME32,
    NANOSCOPE_FILE_TYPE_BROKEN
} NanoscopeFileType;
```

**Comment by dineshpinto** [comment]
@scholi I've forwarded you the file

**Comment by scholi** [comment]
I have prepared a fix. Could you try it.
I have tried it on 4 different files. Hopeful it will be more stable, but Bruker is the worst format ever inverted. The header contains a lot of incorrect values....

**Comment by scholi** [comment]
@dineshpinto I have added the unittest and the header of some Bruker data for the unittest. the data contains only the header to save space and I have added a mock_data argument in Bruker.get_channel() to skip the missing data in the file

**Comment by dineshpinto** [comment]
@scholi the fixes look good, all tests are passing. Did some minor restructuring and formatting, and will publish a new release at `v0.6.1` 

cc @nihtmusic

**Comment by nihtmusic** [comment]
Awesome!  I will hit it a try…much appreciated!

Kurt
