### ISSUE TITLE
show_summary can't find funit

### ISSUE THREAD

**Issue by AlexHenderson** [scholi/pySPM#44]
Asking for a summary of a .ITA file reports an error. 

Line 251 of ITM.py is
from . import funit

Should be 
from .utils import funit

:)

**Comment by dineshpinto** [comment]
Fixed in https://github.com/scholi/pySPM/commit/467f6c1fa31b5cbf6fe887dc5c9a6ff1a2f1b2ac and `pyspm v0.6.2`
