### ISSUE TITLE
Weird topography values

### ISSUE THREAD

**Issue by ezatterin** [scholi/pySPM#7]
Hi,

The 'Height Sensor' or 'Z sensor' channel values (i.e. the topography), seem to be a bit weird. For example:

```python
scan = PfmFile(filelist[0])

chan = scan.get_channel()
xsize, ysize, unit = scan.get_size() # defined by me

fig, ax = plt.subplots(1,1)

im = ax.imshow(chan.pixels, extent=[0,xsize,0,ysize])
ax.set_title('{0} [{1}]'.format(chan.channel, chan.zscale))

append_colorbar(ax, im, label_size=10) # defined by me
```

Results in, as compared to Gwyddion:

pySPM    |  Gwyddion
:---------:|:--------------:
![image](https://user-images.githubusercontent.com/15064659/57518254-889a5f00-7310-11e9-939b-a79753bcb544.png) | ![image](https://user-images.githubusercontent.com/15064659/57518267-905a0380-7310-11e9-8966-1cdcd400e504.png)

Note that in both cases the minimum of the data has been shifted to zero (but not doing it still shows weird values). The 'nm' label has been produced via `chan.zscale` so should be consistent. Any ideas?

Cheers,

Edoardo

**Comment by scholi** [comment]
Thank you for reporting this bug. Something is definitely strange. Could you share your data so that I can test and debug the problem?

Cheers,

Olivier

**Comment by ezatterin** [comment]
There you go, thanks!

[e17089.0_00001.spm.zip](https://github.com/scholi/pySPM/files/3165917/e17089.0_00001.spm.zip)

**Comment by scholi** [comment]
Ok it should be fixed.  I get:
![image](https://user-images.githubusercontent.com/988485/57529905-4ab03180-7336-11e9-92db-3a48201a373a.png)
which is the correct range, but with an offset as I get negative values

**Comment by ezatterin** [comment]
Awesome:

```python
scan = pySPM.Bruker(filelist[0])
chan = scan.get_channel()
p = chan.zero_min().show()
plt.colorbar(p)
````
![image](https://user-images.githubusercontent.com/15064659/57531323-0f5f3400-7331-11e9-9a9d-73cf050a1afd.png)

Thank you!

**Comment by scholi** [comment]
ahah. You know some function better than myself now. I forgot that _zero_min()_ existed...

Keep me updated if you fiund other bugs. I don't use the Bruker module so much anymore and only with the old fileformat...

Regards

**Comment by rejmar16** [comment]
Hi,

I am dealing with the same problem. That topography shows weird value.

`import pySPM

ScanB = pySPM.Bruker("SiC_E9_toughness_P1_1.spm")
topoB = ScanB.get_channel('Height')


fig, ax = plt.subplots(1, 2, figsize=(21, 8))
im = topoB.show(ax=ax[0],cmap='hot')
divider1 = make_axes_locatable(ax[0])
cax1 = divider1.append_axes("right", size="5%", pad=0.05, aspect=16)
cbar1 = plt.colorbar(im, cax=cax1)#,  

topoB.plot_profile(0,290,511,290,ax=ax[1],img=ax[0])

plt.tight_layout()
plt.show()`

![problem](https://user-images.githubusercontent.com/30523621/100297390-964c1f80-2f5c-11eb-8f8f-5d0c72129276.png)

Here you can find raw data:

[SiC_E9_toughness_P1_0.zip](https://github.com/scholi/pySPM/files/5599938/SiC_E9_toughness_P1_0.zip)

I am using version 0.2.21.

Any idea, how to fix it.

Thanks,
Martin

**Comment by scholi** [comment]
Can you try to execute `scan.get_channel(debug=True)` ? It will then print some scaling information...

**Comment by scholi** [comment]
OK I think I found the bug. Somehow Bruker set incorrectly the number of byte per pixel. I could fix it for one of your image. Could you update pySPM and double check with your other images to see if this works?

**Comment by rejmar16** [comment]
Hi Scholi,

Thank you for looking at this issue. I upgraded the pySPM library (pip install -U pySPM). However, I do not see any difference. Still version 0.2.21, and I get the same value as before for height.

This `scan.get_channel(debug=True)` returned 'Channel Height Sensor not found'

Martin

**Comment by scholi** [comment]
Ah yes I have pushed it to github only. I need to make a new package, but it require testing first. for that you need to download the library from github and execute setup.py as follow
`python setup.py install`

for the bug with the height sensor it is because you should use
`scan.get_channel('Height', debug=True)`

**Comment by scholi** [comment]
I have uploaded packaghe 0.2.22. You can get it with pip now:
`pip install -U pySPM`

**Comment by rejmar16** [comment]
Thanks, it works for all checked maps (pySPM vs Gwyddion).

Best
Martin
